spring.application.name=veterinaria-pet-clinic

# ✅ PostgreSQL DATABASE (PRODUCCIÓN O DESARROLLO)
spring.datasource.url=jdbc:postgresql://localhost:5432/pet_clinic
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (ajusta según tu flujo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8

# Logging
logging.level.root=INFO
logging.level.com.veterinariapetCcinic=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO